[workspace]
members = [
    "example",
    "ipp-headers-sys",
    "ipp-sys-build-help",
    "ipp-sys",
    "link-ippcore",
    "link-ippvm",
    "link-ippcv",
    "link-ippdc",
    "link-ippcp",
    "link-ippi",
    "link-ipps",
    ]
